### ISSUE TITLE
installtion

### ISSUE THREAD

**Issue by gvsurenderreddy** [flashwave/whois-php#2]
Hello sir,
Can you tell me how to install and use

**Comment by flashwave** [comment]
it's available through [composer](https://getcomposer.org/) as [flashwave/whois-php](https://packagist.org/packages/flashwave/whois-php)
as for an example the [whois page on my website](https://flash.moe/whois/) uses this library, the source of which is [available here](https://github.com/flashwave/flash.moe/blob/master/app/Controllers/WhoisController.php), primarily in the `lookup` function

i should really just add this to the readme haha, good luck with whatever you want to do with it!
